apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todo-app-backend
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: todo-repo
  interval: 10m
  path: ./backend-conf/manifests # Path tells where to find the files.
  prune: true # This will make sure that deleting the file will delete the resource
  validation: client # Who validates the objects. Server or the client.
